[build]
  command = "bun run server && bun run build"
  publish = "client/public"

[functions]
  server = "bun run server"
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[context.production]
  command = "bun run start"
  functions = ["server"]

[context.deploy-preview]
  command = "bun run start"
  functions = ["server"]
