[build]
  command = "bun run dev"
  publish = "client/public"

[functions]
  server = "bun run server"

[context.production]
  command = "bun run start"
  functions = ["server"]

[context.deploy-preview]
  command = "bun run start"
  functions = ["server"]