networks:
  development:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    networks:
      - development
    
  db:
    image: postgres:16.4-alpine
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "db"
    ports:
      - "5435:5435"
    networks:
      - development

  frontend:
    build: 
      context: ./client
    networks:
      - development

  backend:
    build: 
      context: ./server
    networks:
      - development